version: 1.0.{build}
image: Visual Studio 2017
configuration: release
environment:
  matrix:
  - Platform: x86
  - Platform: x64
build:
  project: NetRipper.sln
  parallel: true
  verbosity: minimal
artifacts:
- path: x64\*.exe
- path: x64\*.dll
- path: x86\*.exe
- path: x86\*.dll
