version: 1.0.{build}
branches:
  only:
  - master
  - v3
image: Visual Studio 2019
configuration: Release
platform: x64
clone_folder: c:\projects\uacme
build:
  project: Source/uacme.sln
  verbosity: normal